---
title: "Cleaned Stop Data"
author: "Amy Zhu, Mengyu Li"
date: "July 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
library(stringr)


#Read data
stop_df <- read.csv("~/Desktop/Berkeley_PD_-_Stop_Data.csv")

# Delete meaningless information and fix data entry errors
stop_df <- stop_df %>%
  mutate(Dispositions = as.character(stop_df$Dispositions)) %>%
  mutate(Dispositions = str_replace(Dispositions, "zz do not use Assist", "")) %>%
  mutate(Dispositions = str_replace(Dispositions, "FA - TIGHT, ", "")) %>%
  mutate(Dispositions = str_replace(Dispositions, "[0]{6}[1]?", "00000"))

# Isolates information about the case into the Other column
stop_df <- stop_df %>%
  mutate(Other = str_replace_all(Dispositions, "[ ,]{0,2}[a-zA-Z0-9]{6}", "")) %>%
  mutate(Other = str_replace_all(Other, "^[ ,]{0,4}", "")) %>%
  mutate(Other = str_replace(Other, ",$", ""))

# Isolates information about the individual(s) into the Dispositions column
OtherInformation <- c( "^M$" = "", ", M$" = "", "M, P$" = "", "P[, ]{0,2}" = "", "AR[, ]{0,2}" = "", "IN[, ]{0,2}" = "", "FC[, ]{0,2}" = "", "CO[, ]{0,2}" = "", "MH[, ]{0,2}" = "", "TOW[, ]{0,2}" = "", "0[, ]{0,2}" = "", "00000[, ]{0,2}" = "")
stop_df <- stop_df %>%
  mutate(Dispositions = str_replace_all(Dispositions, OtherInformation)) %>%
  mutate(Dispositions = str_replace_all(Dispositions, "[, ]{0,2}$", ""))

totalIncidentsNumber <- nrow(stop_df)
typeone <- stop_df %>%
    filter(Other == "" & Dispositions != "")
typeoneNumber = nrow(typeone)
typetwo <- stop_df %>%
    filter(Other != "" & Dispositions == "")
typetwoNumber = nrow(typetwo)
typethree <- stop_df %>%
    filter(Other != "" & Dispositions != "")
typethreeNumber = nrow(typethree)

    

# Arranges information in the Dispositions column into separate objects for each individual involved 
stop_df <- stop_df %>%
  separate(Dispositions, into = c("1", "2", "3", "4", "5"), extra = "merge", fill = "right") %>%
  gather(key = Individual, value = Dispositions, -Incident.Number, -Incident.Type, -Call.Date.Time, -Other, -Location) %>%
  na.omit() %>%
  arrange(Incident.Number)

# Separates information about the individual into 6 columns describing race, gender, age, reason, enforcement, and car search
stop_df <- stop_df %>%
    filter(nchar(Dispositions) == 6) %>%
      mutate(Race = substr(Dispositions,1,1)) %>%
        mutate(Gender = substr (Dispositions,2,2)) %>%
          mutate(AgeRange = substr (Dispositions,3,3)) %>%
            mutate(Reason = substr(Dispositions,4,4)) %>%
              mutate(Enforcement = substr(Dispositions,5,5)) %>%
                 mutate(CarSearch = substr(Dispositions,6,6))

ageVector <- c("1" = "0-18", "2" = "18-29", "3" = "30-39", "4" = "40+")
stop_df$AgeRange = str_replace_all(stop_df$AgeRange, ageVector)

stop_df$Reason <- str_replace(stop_df$Reason, "E", "W")


write.csv(stop_df, "cleaned_stop_data.csv", row.names = FALSE)
View(stop_df)

```

