---
title: "paper1"
author: "Amy Zhu; Mengyu Li; Rebecca Reus; Shangjun Jiang"
date: "2 August 2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(ggmap)
library(tidyr)
library(readr)
library(plyr)
library(dplyr)
library(ggvis)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(readr)
library(data.table)
library(rworldmap)
library(maps)
library(mapdata)
library(maptools)
library(scales)
library(RgoogleMaps)
library(tmap)
library(sp)
library(rgdal)
library(rgeos)
library(RColorBrewer)
```

```{r, echo=FALSE}
############################## location data ############################## 
mergedf <- readRDS( 'StopData_merged.rds' )

## Location info:
latmax <- max(mergedf$lat, na.rm = TRUE) 
latmin <- min(mergedf$lat, na.rm = TRUE)
lonmax <- max(mergedf$long, na.rm = TRUE) 
lonmin <- min(mergedf$long, na.rm = TRUE)
latvals <- c(latmin, latmax)
lonvals <- c(lonmin, lonmax)

## Make the variables factors:
mergedf$CarSearch <- factor(mergedf$CarSearch)
levels(mergedf$CarSearch) <- c("No Search", "Search")  

mergedf$Race <- factor(mergedf$Race)
levels(mergedf$Race) <- c("Asian", "Black", "Hispanic", "Other", "White")

mergedf$Enforcement <- factor(mergedf$Enforcement)
levels(mergedf$Enforcement) <- c("Arrest", "Citation", "Other", "Warning")

mergedf$Reason <- factor(mergedf$Reason)
levels(mergedf$Reason) <- c("Other", "Investigation", "Probation/Parole", "Reasonable Suscipcion", "Traffic", "Wanted")

mergedf <- mergedf %>%
  mutate(Arrest = ifelse( 
    as.character(Enforcement) == "Arrest", 
    "Arrested",
    "Not Arrested") ) %>%
  mutate(Arrest = factor(Arrest))

v <- factor(mergedf$Other)
levels(v)

mergedf <- mergedf %>%
  mutate(Emergency.Psych.Eval = ifelse( str_detect(as.character(Other), "MH"), 
                                        yes = "Yes",
                                        no = "No") )

mergedf$Emergency.Psych.Eval <- factor(mergedf$Emergency.Psych.Eval)

### BerkeleyMap 
berkMap = map = get_map(location = c( lon = mean(lonvals), lat = mean(latvals) ), zoom = 14)


```

# Get Shapefiles Again
```{r, echo=FALSE}
blocks <- readOGR("Census_Tract_Polygons2010","Census_tracts_2010", verbose = TRUE)
locationCensusFiles <- "Census_Tract_Polygons2010"
blocks <- readOGR(locationCensusFiles,"Census_tracts_2010", verbose = TRUE)
b2 <- spTransform(blocks, CRS("+proj=longlat +datum=WGS84"))
b3 <- fortify(b2)
```

## Population by census block group:
```{r,echo=FALSE}
shpfile <- "Census_tracts_2010.shp"
sh <- readShapePoly("Census_Tract_Polygons2010/Census_tracts_2010.shp")
sh@data$ID <- as.numeric(sh@data$ID)

# Read in the demographic data and merge on Neighbourhood Id
demo <- read.csv(file="Census_tracts_2010.csv", header = TRUE)
sh2 <- merge(sh, demo, by='ID')

# Set the palette
p <- colorRampPalette(c("white", "red"))(128)
palette(p)

# Scale the total population to the palette
pop <- sh2@data$TotalPop.x

cols <- (pop - min(pop))/diff(range(pop))*127+1
plot(sh, col=cols)

```
