---
title: "SHINY APP"
author: "Shangjun Jiang"
date: "2 August 2016"
output: html_document
runtime: shiny
---

```{r}
setwd("~/Desktop/Stats R/PROJECT/finalproject_angry_ladies/final_paper")
```


```{r}

             fill = c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(ggmap)
library(tidyr)
library(plyr)
library(dplyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(readr)
library(data.table)
library(rworldmap)
library(maps)
library(mapdata)
library(maptools)
library(scales)
library(RgoogleMaps)
library(tmap)
library(sp)
library(rgdal)
library(rgeos)
library(RColorBrewer)

```


```{r}
## Read in the Data:
#finaldf <- readRDS( 'StopData_finaldf.rds' )
mergedf <- readRDS( 'StopData_merged.rds' )
```

```{r}
## Location info:
latmax <- max( mergedf$lat, na.rm = TRUE ) 
latmin <- min( mergedf$lat, na.rm = TRUE )
lonmax <- max( mergedf$long, na.rm = TRUE ) 
lonmin <- min( mergedf$long, na.rm = TRUE )
latvals <- c( latmin, latmax )
lonvals <- c( lonmin, lonmax )
```

```{r}
## Make the variables factors:
mergedf$CarSearch <- factor(mergedf$CarSearch)
levels(mergedf$CarSearch) <- c("No Search", "Search")  

mergedf$Race <- factor(mergedf$Race)
levels(mergedf$Race) <- c("Asian", "Black", "Hispanic", "Other", "White")

mergedf$Enforcement <- factor(mergedf$Enforcement)
levels(mergedf$Enforcement) <- c("Arrest", "Citation", "Other", "Warning")

mergedf$Reason <- factor(mergedf$Reason)
levels(mergedf$Reason) <- c("Other", "Investigation", "Probation/Parole", "Reasonable Suscipcion", "Traffic", "Wanted")

mergedf <- mergedf %>%
  mutate(Arrest = ifelse( 
    as.character(Enforcement) == "Arrest", 
    "Arrested",
    "Not Arrested") ) %>%
  mutate(Arrest = factor(Arrest))

v <- factor(mergedf$Other)
levels(v)

mergedf <- mergedf %>%
  mutate(Emergency.Psych.Eval = ifelse( str_detect(as.character(Other), "MH"), 
                                        yes = "Yes",
                                        no = "No") )

mergedf$Emergency.Psych.Eval <- factor(mergedf$Emergency.Psych.Eval)

?write.csv

write.csv(mergedf, "mergedf.csv", row.names = F)

berkMap = map = get_map(location = c( lon = mean(lonvals), lat = mean(latvals) ), zoom = 14)
```

## MAP 4:
```{r}

ggmap(berkMap) +
  geom_point(aes(x = long, y = lat, colour = Reason), data = mergedf, alpha = 0.7, size = 3) +
  theme ( 
		panel.grid.major = element_blank (), # remove major grid
		panel.grid.minor = element_blank (),  # remove minor grid
		axis.text = element_blank (), 
		axis.title = element_blank (),
		axis.ticks = element_blank ()
		) + ggtitle("All BPD Stops, by Reason 2015-2016") +
    facet_wrap( ~ Reason , ncol = 2)
```


```{r}

############################## stop data ############################## 
stop_by <- read_csv("cleaned_stop_data.csv")

stop_by$Call.Date.Time <- mdy_hm(stop_by$Call.Date.Time)
stop_by$AgeRange <- as.factor(stop_by$AgeRange)

stop_by <- stop_by %>%
  mutate(Hour = as.integer(hour(Call.Date.Time))) %>%
  mutate(Day = as.factor(as.integer(wday(Call.Date.Time))))

stop_by$Race<- stop_by$Race %>% 
  str_replace("A", "Asian") %>% 
  str_replace("B", "Black") %>% 
  str_replace("H", "Hispanic") %>% 
  str_replace("O", "Other") %>% 
  str_replace("W", "White")

stop_by$Gender<- stop_by$Gender %>% 
  str_replace("F", "Female") %>% 
  str_replace("M", "Male") 

stop_by$Reason <- stop_by$Reason %>% 
  str_replace("I", "Investigation") %>% 
  str_replace("T", "Traffic") %>% 
  str_replace("R", "Reasonable Suspicion") %>% 
  str_replace("R", "Probation/ Parole") %>% 
  str_replace("W", "Wanted")

stop_by$Enforcement <- stop_by$Enforcement %>% 
  str_replace("A", "Arrest") %>% 
  str_replace("C", "Citation") %>% 
  str_replace("O", "Other") %>% 
  str_replace("W", "Warning")

stop_by$CarSearch <- stop_by$CarSearch %>% 
  str_replace("S", "Search") %>% 
  str_replace("N", "No Search")

write.csv(stop_by, "stop_data_jenny.csv", row.names = F)

```


```{r}
p1 <- ggplot(stop_by)+
  geom_bar(aes(x=Race),
           fill = c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF"))+
  labs(title = "Stop data by race",
       x = "Race",
       y = "Counts")

p2 <- ggplot(race)+
  geom_bar(aes(x=Description, 
               y=Counts),
           stat = "identity", 
           fill = c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF"))+
  labs(title = "Demographic race data",
       x = "Race",
       y = "Counts")

multiplot(p1, p2,cols=2)

## asian #FFCC00
## black: #000000
## hispanic: #330099
## other: #66FFCC
## white: #FFFFFF

c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF")

```






```{r}
stop_by
m <- subset(stop_by, Hour = "7") %>% 
  group_by(Race) %>% 
  tally() %>% 
  arrange(desc(n))

rrr <- subset(stop_by, Hour = "7") %>% 
  group_by(AgeRange) %>% 
  tally() 
rrr$Race<-as.factor(rrr$Race)

ggplot(rrr)+
  geom_bar(aes(x=AgeRange, y = n),
           stat = "identity")

ggplot(rrr)+
  geom_bar(aes(x=AgeRange, y = n),
           stat = "identity",
           fill = c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF"))

rrr <- subset(stop_by, Hour = "7") %>% 
  group_by(Race) %>% 
  tally() 




           fill = c("red", "yellow", "white", "blue"))
           fill = c("#FFCC00","#000000","#330099","#66FFCC","#FFFFFF"))

m[sort(m$n, decreasing=T),]
m
m[order(-m[,3],m[,1]),]

arrange(m,desc(n))

```


```{r}
subset(stop_by, Hour = "7") %>% 
    group_by(Agerange) %>% 
    tally() 


  
  test <- subset(stop_by, Hour = input$hour) %>% 
    group_by(input$dataset) %>% 
    tally() 

  test$Race<-as.factor(test$Race)
  
  
  
  
     sidebarPanel(
      sliderInput('hour',
                  'HOUR: ',
                  0, 24, value=7,
                  animate = T),
      
```



```{r}
ggmap(berkMap) +
  stat_density2d(aes(x = long, y = lat, fill = ..level.., alpha = ..level..),
    bins = I(5), geom = "polygon", data = mergedf ) +
  scale_fill_gradient2( "Stop Density",
    low = "white", mid = "orange", high = "red", midpoint = 25) +
  labs(x = "Longitude", y = "Latitude") + facet_wrap(~ AgeRange) +
  scale_alpha(range = c(.2, .55), guide = FALSE) +
  ggtitle("BPD Stop Contour Map of Berkeley by Age Range") +
  guides(fill = guide_colorbar(barwidth = 1.5, barheight = 10))


```




