---
title: "Jail"
author: "Shangjun Jiang"
date: "30 July 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("~/Desktop/Stats R/PROJECT/finalproject_angry_ladies/Jenny_Analysis")
```


```{r}
library(rvest)
library(xml2)
library(ggplot2)
library(lubridate)
library(stringr)
library(dplyr)
library(tidyr)
library(readr)
library(scales)
library(ggvis)
```


```{r}
jail <- read.csv("Berkeley_PD_Log_-_Jail_Bookings.csv")
jail$Age <- as.integer(jail$Age)
jail$Age[jail$Age<20] <- "0-19"
jail$Age[jail$Age>=20 & jail$Age<30] <- "20-29"
jail$Age[jail$Age>=30 & jail$Age<40] <- "30-39"
jail$Age[jail$Age>=40 & jail$Age<50] <- "40-49"
jail$Age[jail$Age>=50 & jail$Age<60] <- "50-59"
jail$Age[jail$Age>=60 & jail$Age<70] <- "60-69"
jail$Age[jail$Age>=70 & jail$Age<80] <- "70-79"
jail$Age <- as.factor(jail$Age)

#jail$Arrest.Date.and.Time<- as.POSIXct(as.character(jail$Arrest.Date.and.Time))
#jail$Booking.Date.and.Time <- as.POSIXct(as.character(jail$Booking.Date.and.Time))

#jail$Arrest.Date.and.Time <- mdy_hms(jail$Arrest.Date.and.Time)
#jail$Booking.Date.and.Time <- mdy_hms(jail$Booking.Date.and.Time)
#jail$Date.Of.Birth <- mdy(as.character(jail$Date.Of.Birth))


names(jail)
#[1] "Booking.Number"        "Booking.Date.and.Time" "Subject"              
#[4] "Race"                  "Sex"                   "Date.Of.Birth"        
#[7] "Age"                   "Height"                "Weight"               
#[10] "Hair"                  "Eyes"                  "Occupation"           
#[13] "Statute"               "Statute.Type"          "Statute.Description"  
#[16] "Arrest.Date.and.Time"  "Case.Number"           "Booking.Agency"       
#[19] "Disposition"  
jail[jail == ""] <- NA
najail <- na.omit(jail)

```



## race and disposition
```{r}
ggplot(najail)+
  geom_bar(aes(x=Disposition,
               fill = Sex))+
  facet_wrap(~Race)

najail$Disposition <- str_replace(najail$Disposition, "NO COMPLAINT", "NC") %>% 
  str_replace("SANTA RITA JAIL", "SRC") %>% 
  str_replace("")


ggplot(najail)+
  geom_bar(aes(x=Disposition,
               fill = Race))+
  facet_wrap(~Sex)+
   scale_x_discrete(labels = function(x) str_wrap(x, width = 5))

```

## demographics data
```{r}
ggplot(najail)+
  geom_bar(aes(x=Age, 
               fill = Race))+
  facet_wrap(~Sex)+
  labs(x= "Age",
       y = "Number of people",
       title = "Jail Data")


```


## occupation data
```{r, eval=F}
najail$Race <- as.factor(najail$Race)
ggplot(najail) +
  geom_bar(aes(x=Occupation,
           fill = Race))
hour(jail$Booking.Date.and.Time)

ggvis(jail,
      x=~hour(Booking.Date.and.Time),
      fill := "pink") %>% 
  layer_bars(width = input_slider(1,20,step=2,label="width"))  


ggvis(jail,
      x=~hour(Arrest.Date.and.Time),
      fill := "pink") %>% 
  layer_bars(width = input_slider(1,20,step=2,label="width"))  

  layer

```



```{r, eval=F}
#group_by hour, count

names(jail)

jail %>% 
  filter(Race == "Black")
?filter


jail<- jail %>% 
  mutate(arresthour =hour(Arrest.Date.and.Time))
#group by arrest hour
newjail<- jail%>% 
  group_by(arresthour) %>% 
  summarise(hourcount=n())
#group by race
new2jail <- jail %>% 
  group_by(Race, arresthour) %>% 
  summarise(racecount=n())
#group by age
new3jail <- jail %>% 
  group_by(Age, arresthour) %>% 
  summarise(agecount=n())


racearrestjail<-left_join(new2jail,newjail, by = "arresthour")

agearrestjail <-left_join(new3jail,newjail,by = "arresthour")


#race arrest plot
ggplot(na.omit(racearrestjail))+
  geom_bar(aes(x=arresthour, 
                     y=(racecount/hourcount),
                     fill = Race),
           stat="identity") +
  facet_wrap(~Race)



```



## Arrest date and booking date 
jail$Arrest.Date.and.Time <- mdy_hms(jail$Arrest.Date.and.Time)
jail$Booking.Date.and.Time <- mdy_hms(jail$Booking.Date.and.Time)


```{r, eval=F}
ggplot(jail)+
  geom_segment(aes(x= hour(Arrest.Date.and.Time), 
               xend = hour(Booking.Date.and.Time),
               y = day(Arrest.Date.and.Time),
               yend = day(Booking.Date.and.Time)))

ggplot(jail)+
  geom_segment(aes(x= hour(Arrest.Date.and.Time), 
                  xend = hour(Booking.Date.and.Time),
                  y= Race,
                  yend=Race))


ggplot(jail)+
  geom_segment(aes(x= hour(Arrest.Date.and.Time), 
                  xend = hour(Booking.Date.and.Time),
                  y= minute(Arrest.Date.and.Time),
                  yend=minute(Booking.Date.and.Time)))


ggplot(na.omit(jail))+
  geom_point(aes(x= hour(Arrest.Date.and.Time), 
                 y= hour(Booking.Date.and.Time),
                 color = Race,
                 shape = Sex))


najail <- na.omit(jail)
najail <- najail %>% 
  mutate(arresthour = hour(Arrest.Date.and.Time)) %>% 
  mutate(bookhour = hour(Booking.Date.and.Time))

nai
najail %>% 
  ggvis(~arresthour,
        ~bookhour,
         fill= ~Race,
        opacity := 0.7) %>%
  layer_points() %>%
  add_tooltip((function(naarrest) najail$arresthour))


```






















